global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false
  image:
    tag: 8.2.3
  elasticsearch:
    disableExporter: true

# Disable identity as part of the camunda platform core
identity:
  enabled: false

optimize:
  enabled: false

# Release label should match Helm release name
prometheusServiceMonitor:
  enabled: true
  labels:
    release: metrics

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  cpuThreadCount: 4
  ioThreadCount: 2
  resources:
    requests:
      cpu: 6000m
      memory: 2000Mi
    limits:
      cpu: 18000m
      memory: 16000Mi
  pvcSize: 10Gi
  persistenceType: memory
  readinessProbe:
    probePath: /actuator/health/readiness
  env:
    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
      value: "false"
    - name: ZEEBE_BROKER_CLUSTER_RAFT_FLUSH_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_CLUSTER_RAFT_FLUSH_DELAYTIME
      value: "5s"
    - name: ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_DISABLEWAL
      value: "true"
    - name: JAVA_TOOL_OPTIONS
      value: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log -XX:+ExitOnOutOfMemoryError -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1100 -Djava.rmi.server.hostname=192.168.0.100 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false 
  service:
    extraPorts:
      - name: jmx
        protocol: TCP
        port: 1099
        targetPort: 1099
      - name: rmi
        protocol: TCP
        port: 1100
        targetPort: 1100

zeebe-gateway:
  replicas: 1
  resources:
  requests:
    cpu: 400m
    memory: 450Mi
  limits:
    cpu: 1000m
    memory: 450Mi


connectors:
  enabled: false
  inbound:
    mode: disabled
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "1000m"

# Disable tasklist (we don't need user tasks)
tasklist:
  enabled: false

operate:
  enabled: false

# Configure elastic search to make it running for local development
elasticsearch:
  enabled: false
  imageTag: 7.17.3
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1536M"

  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 15Gi
