global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false
  image:
    tag: 8.1.11

# Disable identity as part of the camunda platform core
identity:
  enabled: false

optimize:
  enabled: false

# Release label should match Helm release name
prometheusServiceMonitor:
  enabled: true
  labels:
    release: metrics

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
  readinessProbe:
    probePath: /actuator/health/readiness
  env:
    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
      value: "false"

zeebe-gateway:
  replicas: 1

connectors:
  enabled: false
  inbound:
    mode: disabled
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "1000m"

# Disable tasklist (we don't need user tasks)
tasklist:
  enabled: false

# Configure elastic search to make it running for local development
elasticsearch:
  imageTag: 7.17.3
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1536M"

  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 15Gi
