global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false
  image:
    tag: 8.3.0-alpha6
  elasticsearch:
    disableExporter: true

# Disable identity as part of the camunda platform core
identity:
  enabled: false

optimize:
  enabled: false

# Release label should match Helm release name
prometheusServiceMonitor:
  enabled: true
  labels:
    release: metrics

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 3
  partitionCount: 6
  replicationFactor: 3
  cpuThreadCount: 4
  ioThreadCount: 2
  resources:
    requests:
      cpu: 6000m
      memory: 16000Mi
    limits:
      cpu: 6000m
      memory: 16000Mi
  pvcSize: 5Gi
  persistenceType: memory
  # extraVolumes:
  #   - name: runtime
  #     emptyDir:
  #       medium: "Memory"
  # extraVolumeMounts:
  #   - name: runtime
  #     mountPath: /usr/local/zeebe/runtime
  readinessProbe:
    probePath: /actuator/health/readiness
  nodeSelector:
    camunda/app: broker
  env:
    - name: TZ
      value: "Europe/Moscow"
    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
      value: "false"
    - name: ZEEBE_BROKER_BACKPRESSURE_ALGORITHM
      value: "aimd"
    - name: ZEEBE_BROKER_BACKPRESSURE_AIMD_INITIALLIMIT
      value: "1000"
    - name: ZEEBE_BROKER_BACKPRESSURE_AIMD_MINLIMIT
      value: "100"
    - name: ZEEBE_BROKER_BACKPRESSURE_AIMD_MAXLIMIT
      value: "2000"
    - name: ZEEBE_BROKER_CLUSTER_RAFT_FLUSH_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_CLUSTER_RAFT_FLUSH_DELAYTIME
      value: "0s"
    - name: ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_DISABLEWAL
      value: "true"
    - name: ZEEBE_BROKER_DATA_SNAPSHOTPERIOD
      value: "1m"
    # - name: ZEEBE_BROKER_DATA_RUNTIMEDIRECTORY
    #   value: "runtime"
    - name: ZEEBE_BROKER_EXPERIMENTAL_FEATURES_ENABLEACTORMETRICS
      value: "true"
    - name: ZEEBE_BROKER_EXPERIMENTAL_FEATURES_ENABLETIMERDUEDATECHECKERASYNC
      value: "true"
    - name: JAVA_TOOL_OPTIONS
      value: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log -XX:+ExitOnOutOfMemoryError -XX:+UseShenandoahGC -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1100 -Djava.rmi.server.hostname=192.168.0.100 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
  service:
    extraPorts:
      - name: jmx
        protocol: TCP
        port: 1099
        targetPort: 1099
      - name: rmi
        protocol: TCP
        port: 1100
        targetPort: 1100

zeebe-gateway:
  replicas: 1
  resources:
  requests:
    cpu: 1000m
    memory: 500Mi
  limits:
    cpu: 2000m
    memory: 900Mi
  nodeSelector:
    camunda/app: gateway
  env:
    - name: TZ
      value: "Europe/Moscow"
    - name: ZEEBE_GATEWAY_LONGPOLLING_ENABLED
      value: "true"
    - name: JAVA_TOOL_OPTIONS
      value: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data -XX:ErrorFile=/usr/local/zeebe/data/zeebe_gateway_error%p.log -XX:+ExitOnOutOfMemoryError -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1101 -Dcom.sun.management.jmxremote.rmi.port=1102 -Djava.rmi.server.hostname=192.168.0.100 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false

connectors:
  enabled: false
  inbound:
    mode: disabled
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "1000m"

# Disable tasklist (we don't need user tasks)
tasklist:
  enabled: false

operate:
  enabled: false
  logging:
    level:
      ROOT: INFO
      io.camunda.operate: INFO
  nodeSelector:
    camunda/app: operate
  resources:
    requests:
      cpu: "1000m"
      memory: "800M"
    limits:
      cpu: "1000m"
      memory: "800M"
  env:
    - name: TZ
      value: "Europe/Moscow"

# Configure elastic search to make it running for local development
elasticsearch:
  enabled: false
  nodeSelector:
    camunda/app: elasticsearch
  imageTag: 7.17.11
  replicas: 3
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  extraEnvs:
    - name: "xpack.security.enabled"
      value: "false"
    - name: "xpack.monitoring.collection.enabled"
      value: "true"
  env:
    - name: TZ
      value: "Europe/Moscow"
  resources:
    requests:
      cpu: "2000m"
      memory: "1536M"
    limits:
      cpu: "2000m"
      memory: "1536M"
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 15Gi
