controller:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  service:
    type: LoadBalancer
  publishService:
    enabled: false
  admissionWebhooks:
    enabled: false
  hostPort:
    enabled: true
  nodeSelector:
    camunda/app: ingress
