controller:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  hostPort:
    enabled: true

  service:
    type: LoadBalancer
    enableHttps: false

  publishService:
    enabled: false

  admissionWebhooks:
    enabled: false

  nodeSelector:
    camunda/app: ingress
