---
elasticsearchHosts: http://elasticsearch-master:9200
imageTag: 7.17.11

kibanaConfig:
  kibana.yml: |
    server.ssl.enabled: false

protocol: http

nodeSelector:
    camunda/app: operate

env:
  - name: TZ
    value: "Europe/Moscow"
