---
elasticsearchHosts: http://elasticsearch-master:9200
image: "bitnami/kibana"
imageTag: 8.8.2

kibanaConfig:
  kibana.yml: |
    server.ssl.enabled: false

protocol: http

nodeSelector:
  camunda/app: elasticsearch
  elk/app: kibana

env:
  - name: TZ
    value: "Europe/Moscow"
