# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    camunda/app: broker
- role: worker
  labels:
    camunda/app: broker
- role: worker
  labels:
    camunda/app: broker
- role: worker
  labels:
    camunda/app: gateway
  extraPortMappings:
  - hostPort: 9600
    containerPort: 30600
    protocol: TCP