# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    camunda/app: broker
- role: worker
  labels:
    camunda/app: broker
- role: worker
  labels:
    camunda/app: broker
- role: worker
  labels:
    camunda/app: gateway
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8081
    protocol: TCP
  - containerPort: 30001
    hostPort: 8082
    protocol: TCP
  - containerPort: 30100
    hostPort: 9600
    protocol: TCP
  - containerPort: 30101
    hostPort: 26500
    protocol: TCP
  - containerPort: 30102
    hostPort: 1101
    protocol: TCP
  - containerPort: 30103
    hostPort: 1102
    protocol: TCP
  - containerPort: 30200
    hostPort: 1099
    protocol: TCP
  - containerPort: 30201
    hostPort: 1100
    protocol: TCP
  - containerPort: 30300
    hostPort: 8083
    protocol: TCP
