apiVersion: v1
kind: Service
metadata:
  name: zeebe-gateway-nodeports
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30600
    port: 9600
  selector:
    app.kubernetes.io/name: zeebe-gateway

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeports
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 3000
  selector:
    app.kubernetes.io/name: grafana
