{
 "title": "Zeebe Workers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_client_requests_sent_messages_total, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(grpc_client_requests_sent_messages_total{namespace=\"$namespace\"}, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(grpc_client_requests_sent_messages_total{namespace=\"$namespace\",application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Grpc metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of requests sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "grpc_client_requests_sent_messages_total{application=\"$application\", namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "{{ methodType }} {{ method }}"
    }
   ]
  },
  {
   "title": "Average number of requests sent per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(grpc_client_requests_sent_messages_total{application=\"$application\", namespace=\"$namespace\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{ methodType }} {{ method }}"
    }
   ]
  },
  {
   "title": "Total number of responses received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "grpc_client_responses_received_messages_total{application=\"$application\", namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "{{ methodType }} {{ method }}"
    }
   ]
  },
  {
   "title": "Average number of responses received per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(grpc_client_responses_received_messages_total{application=\"$application\", namespace=\"$namespace\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{ methodType }} {{ method }}"
    }
   ]
  },
  {
   "title": "Max response time",
   "type": "timeseries",
   "description": "The total time taken for the client to complete the call, including network delay",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "grpc_client_processing_duration_seconds_max{application=\"$application\", namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "{{ methodType }} {{ method }} {{ statusCode }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "description": "The total time taken for the client to complete the call, including network delay",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(grpc_client_processing_duration_seconds_sum{application=\"$application\", namespace=\"$namespace\", instance=\"$instance\"}[1m])/ irate(grpc_client_processing_duration_seconds_count{application=\"$application\", namespace=\"$namespace\", instance=\"$instance\"}[1m]) ",
     "legendFormat": "{{ methodType }} {{ method }} {{ statusCode }}"
    }
   ]
  },
  { "title": "Worker metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Jobs actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "camunda_job_invocations_total{namespace=\"$namespace\", application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{ action }} {{ type }}"
    }
   ]
  },
  {
   "title": "Average Job RPS per 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(camunda_job_invocations_total{namespace=\"$namespace\", application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{ action }} {{ type }}"
    }
   ]
  }
 ]
}